web:
  build: .
  dockerfile: Dockerfile-development
  links:
   - db
  # command: ./node_modules/.bin/nodemon --inspect=0.0.0.0:5858
  ports:
   - "8000:8000"
   - "5858:5858"
  volumes:
   - .:/usr/src/app/
  environment:
   NODE_ENV: development 
   MONGO_URL: mongodb://db:27017/mern-starter
db:
  image: mongo:latest
  ports:
   - "27017:27017"

